# fly.toml app configuration file generated for mailnow on 2023-10-14T23:15:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mailnow"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
